### ISSUE TITLE
The session is invalid

### ISSUE THREAD

**Issue by wurgun** [robertsLando/node-red-contrib-whatsappbot#10]
Hello,

When I scan the Qr code, I get an invalid session error. After the error message the process restarts and generates a new qr code.

![image](https://user-images.githubusercontent.com/33448883/96247191-75ce9400-0fb2-11eb-85d1-d92f94f05144.png)

Regards.

**Comment by robertsLando** [comment]
Try to delete any session file you find in node-red directory and retry

**Comment by wurgun** [comment]
Hi Daniel,

I just installed a clean node-red on another server. The same problem continues.

Regards.

**Comment by robertsLando** [comment]
Try to update wa automate to latest version

**Comment by wurgun** [comment]
it works. Thank you for your help.
