### ISSUE TITLE
Error to send message

### ISSUE THREAD

**Issue by chameleonbr** [robertsLando/node-red-contrib-whatsappbot#11]
Hi, on the last version if I try to send message console return this error:
[error] [whatsapp-bot:2fdea1c1.c396ce] Requested api "sendMessageToId" Cannot read property 'evaluate' of undefined
I tried to send message using dashboard example with Contact ID NUMBER@c.us

**Comment by robertsLando** [comment]
@chameleonbr after the update the `page` reference was changed to `_page`, now it's working again

**Comment by robertsLando** [comment]
@chameleonbr Published version 0.2.1 now, check it out :)
