### ISSUE TITLE
What are the features of this Repo?

### ISSUE THREAD

**Issue by dmastag** [robertsLando/node-red-contrib-whatsappbot#2]
First of all amazing Work
Have been able to use this to get and send messages to whatsapp

Now I would like to ask what else I can do now?
Would be awesome if i can send documents or images and receive them

I tried to send a location using this function but its not working as intended.
Does this only support receiving and sending messages now?

```
node.send({topic: 'sendText', payload: ["XXX",
  25.6801987,
  -100.4060626,
  'Some address, Washington DC',
  'Subtitle']})
```

**Comment by robertsLando** [comment]
You have to use “sendLocation” for a location. Check sulla apis for more info. It actually support all kind of functiona

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by dmastag** [comment]
Hi @robertsLando 
Its working now, thanks
