### ISSUE TITLE
Cannot keep Session

### ISSUE THREAD

**Issue by dmastag** [robertsLando/node-red-contrib-whatsappbot#3]
Hi there,
So i notices that every time I deploy changes to my flow I need to re-authenticate.
Am not sure if this is a problem because I am using docker or anything else.

Is there a way to keep the session?

**Comment by robertsLando** [comment]
I’m actually working on it. If you stop/restart node-red it keeps the session saved but with a deploy it doesn’t, in order to keep the session the client must be closed correctly but seems it doesn’t close

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by vandreicerqueira** [comment]
> I’m actually working on it. If you stop/restart node-red it keeps the session saved but with a deploy it doesn’t, in order to keep the session the client must be closed correctly but seems it doesn’t close —————— Daniel - Software Engineer Support me at: Github sponsors
> […](#)
> On 13 Apr 2020, at 06:52, Julian Alimin ***@***.***> wrote: ﻿ Hi there, So i notices that every time I deploy changes to my flow I need to re-authenticate. Am not sure if this is a problem because I am using docker or anything else. Is there a way to keep the session? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@robertsLando, maybe you should try using [open-wa/wa-automate](https://www.npmjs.com/package/@open-wa/wa-automate) instead of sulla, it simply works, even when one reboots the server!

**Comment by robertsLando** [comment]
@vandreicerqueira I prefer to keep using sulla for now

**Comment by RehDen** [comment]
How are you doing in the recovery session?

**Comment by robertsLando** [comment]
I have to update to latest sulla version and it should work :)

**Comment by dmastag** [comment]
@robertsLando exciting to hear :-)

**Comment by robertsLando** [comment]
I ended up with switching to https://github.com/open-wa/wa-automate-nodejs#capturing-qr-code

Please use version 0.1.0 available on npm from now

**Comment by dmastag** [comment]
@robertsLando this was unexpected

Considering that I have to pay monthly to be able to send messages to unknown numbers which is essential in one of my apps

**Comment by robertsLando** [comment]
Are you sure? You could just use sendMessageToId for that 

---

Daniel

**Comment by robertsLando** [comment]
Tomorrow I will submit a fix for this. Sorry

---

Daniel

**Comment by dmastag** [comment]
Yes, am sure.

https://github.com/open-wa/wa-automate-nodejs#starting-a-conversation
![image](https://user-images.githubusercontent.com/5745805/83704042-36bf2800-a63b-11ea-8d6e-2f8787b669ec.png)

And when I checked the Price at gumroad
https://gumroad.com/l/BTMt

![image](https://user-images.githubusercontent.com/5745805/83704078-522a3300-a63b-11ea-8322-bec46e1904a8.png)

£60 a month is quite a sum

**Comment by robertsLando** [comment]
As I said, let me submit a patch for this, you will not have to pay anything 

---

Daniel

**Comment by robertsLando** [comment]
@dmastag Please use version 0.1.1 and the api `sendMessageToId`. Check readme docs for more info

**Comment by RehDen** [comment]
I left the session to be tested. Today I discovered that the session is not working. error - no authorization.
in the program wat sap is displayed - the session is active.
I can’t log in anymore. I do not understand why. I reinstalled everything ... there is no more authorization. I also noticed the vatsap in the program - earlier the Windows session was displayed. now mac os.
lack of authorization update function. if authorization is not successful then you have to restart all threads - Restart Flows

**Comment by dmastag** [comment]
I am having a similar problem. It was working earlier not I can't seem to send anything.
Even though it says that it has been authorized.

**Comment by robertsLando** [comment]
Could you try to uninstall and install again the node please? I have expected the same problem and seems it was caused by puppeteer version

**Comment by robertsLando** [comment]
@RehDen If you are not able to login anymore please go to `~/.node-red` directory and removev `session.data.json` file

**Comment by dmastag** [comment]
Ok, got it working.
Also just realized why you had to move from Sulla and the discussions happening in the Repo.

**Comment by robertsLando** [comment]
@dmastag Glad you fixed it. Sulla is almost unmaintained that's why my decision. I have write permissions on it but I have no time to keep it updated. wa-automate requires license for some features but I can create patches for them

**Comment by dmastag** [comment]
There is also a lot of conversation going on about Venom.
Tested it for another project and seems to work fine and has some contributors and is free.

What do you think about it?

**Comment by robertsLando** [comment]
I have received a collaboration request but the code is taken from sulla and I don't know how many changes have been made (at first sight it seems just like a fork with namespace changed, no features added).

**Comment by dmastag** [comment]
Yes, and it seems odd.
Right now I am just waiting for a couple of months to look hot it goes.

**Comment by robertsLando** [comment]
wa-automate is also a fork of sulla but it's out from many months and has lot of users :)

**Comment by dmastag** [comment]
It is isn't it. And the funny thing is they used to be called sula-hotfix.

**Comment by robertsLando** [comment]
>  they used to be called sula-hotfix.

Yes that was before he (the author of sulla-hotfix) started to make money with it :smile: 

He has also removed sulla from the readme because lot users where still using it.
