### ISSUE TITLE
every time I receive 4 duplicate messages

### ISSUE THREAD

**Issue by antonag** [robertsLando/node-red-contrib-whatsappbot#6]
Dear Lando,
I tested today, everything is ok, but each time I send/receive/confirmation,  I  receive 4 duplicate messages with the same payload, different "_msgid", but the payload is the same.

![image](https://user-images.githubusercontent.com/56447712/87589156-d21fd000-c6b2-11ea-885b-cfe5f6632348.png)

Thanks
Antonio

**Comment by robertsLando** [comment]
@antonag Does this happen even if you restart node-red?

**Comment by antonag** [comment]
I restart and now is ok.    When I send, I receive 3 onAck msg  with 3 diferent ack in the payload:
ack =1, sent
ack = 2, received
ack = 3, readed

Thanks.
Antonio

**Comment by antonag** [comment]
Dear Lando, when I restart node-red everything is ok, but when I restart the flows is not mor working until restart node-red...

In the cmd log I receive this error:
(node:14416) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit.

![image](https://user-images.githubusercontent.com/56447712/87734904-e68ec600-c7a1-11ea-8e67-2eba8630d820.png)

**Comment by robertsLando** [comment]
Oh ok you should filter outcoming packets to just sent or “received” acks to dedupe them

---

Daniel
