### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by jorgenv-create** [robertsLando/node-red-contrib-whatsappbot#7]
Hello, 
I tried to install this in a docker container but i get the following error:

 Not Found - GET https://registry.npmjs.org/@open-wa%2fwa-decrypt - Not found

**Comment by robertsLando** [comment]
@jorgenv-create I need more log output

**Comment by jorgenv-create** [comment]
140 warn notsup Unsupported engine for @open-wa/wa-automate@1.9.105: wanted: {"node":">=12.18.3"} (current: {"node":"10.21.0","npm":"6.14.4"})
141 warn notsup Not compatible with your version of node/npm: @open-wa/wa-automate@1.9.105
142 verbose notsup Not compatible with your version of node/npm: @open-wa/wa-automate@1.9.105
142 verbose notsup Required: {"node":">=12.18.3"}
142 verbose notsup Actual:   {"npm":"6.14.4","node":"10.21.0"}
143 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@open-wa%2fwa-decrypt - Not found
143 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
143 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
144 verbose statusCode 404
145 verbose pkgid @open-wa/wa-decrypt@^2.0.1
146 verbose cwd /usr/src/node-red
147 verbose Linux 4.19.107-Unraid
148 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-whatsappbot" "--save"
149 verbose node v10.21.0
150 verbose npm  v6.14.4
151 error code E404
152 error 404 Not Found - GET https://registry.npmjs.org/@open-wa%2fwa-decrypt - Not found
153 error 404
154 error 404 '@open-wa/wa-decrypt@^2.0.1' is not in the npm registry.
155 error 404 You should bug the author to publish it (or use the name yourself!)
156 error 404 It was specified as a dependency of '@open-wa/wa-automate'
157 error 404 Note that you can also install from a
158 error 404 tarball, folder, http url, or git url.
159 verbose exit [ 1, true ]

i found this, it says unsuported version, but my node-red docker is up to date.

**Comment by robertsLando** [comment]
@jorgenv-create I think this is self explained:

`wanted: {"node":">=12.18.3"} (current: {"node":"10.21.0","npm":"6.14.4"})`

Your nodejs version is lower then 12.18.3
